(import (chicken file)
        (chicken load)
        (chicken process-context))

(define (cluck-template-trim-trailing-slash path)
  (let ((len (string-length path)))
    (if (and (> len 0)
             (char=? (string-ref path (- len 1)) #\/))
        (substring path 0 (- len 1))
        path)))

(define (cluck-template-normalize-directory dir)
  (if (and dir (> (string-length dir) 0))
      (let ((len (string-length dir)))
        (if (char=? (string-ref dir (- len 1)) #\/)
            dir
            (string-append dir "/")))
      #f))

(define (cluck-template-root)
  (let loop ((i (- (string-length (program-name)) 1)))
    (if (< i 0)
        (string-append (current-directory) "/")
        (if (char=? (string-ref (program-name) i) #\/)
            (substring (program-name) 0 (+ i 1))
            (loop (- i 1))))))

(define (cluck-template-cluck-root root)
  (or (let ((home (get-environment-variable "CLUCK_HOME")))
        (cluck-template-normalize-directory home))
      (let ((vendor (string-append (cluck-template-trim-trailing-slash root)
                                   "/vendor/cluck/")))
        (and (file-exists? (string-append vendor "cluck-init.scm"))
             vendor))
      (let ((local (string-append (cluck-template-trim-trailing-slash root)
                                  "/cluck/")))
        (and (file-exists? (string-append local "cluck-init.scm"))
             local))
      (cluck-template-normalize-directory root)))

(define (cluck-template-load-runtime! root)
  (let ((cluck-root (cluck-template-cluck-root root)))
    (dynamic-wind
      (lambda ()
        (change-directory cluck-root))
      (lambda ()
        (load "cluck.scm"))
      (lambda ()
        (change-directory root)))
    cluck-root))

(define (cluck-template-load-app! root path)
  (load-file (string-append root path)))
