(import (chicken file)
        (chicken load)
        (chicken process-context))

(define (script-root)
  (let loop ((i (- (string-length (program-name)) 1)))
    (if (< i 0)
        (string-append (current-directory) "/")
        (if (char=? (string-ref (program-name) i) #\/)
            (substring (program-name) 0 (+ i 1))
            (loop (- i 1))))))

(let ((root (script-root)))
  (handle-exceptions exn #t
    (create-directory (string-append root "../build")))
  (load (string-append root "../src/cluck-init.scm"))
  (load-file (string-append root "../examples/cluck/ro/core/commands.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/json.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/docs.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/help.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/workspace.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/projects.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/items.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/events.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/sync.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/doctor.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/reindex.clk"))
  (load-file (string-append root "../examples/cluck/ro/core/route.clk"))
  (load-file (string-append root "../examples/cluck/ro/bootstrap-core-aliases.scm"))
  (load-file (string-append root "../examples/cluck/ro/src/app.clk"))
  (load-file (string-append root "../examples/cluck/ro/main.clk"))
  (load-file (string-append root "ro-cli.clk")))
