(import scheme
        (chicken base)
        (chicken load)
        (chicken process-context))

(begin-for-syntax
  (import (chicken file)
          (chicken process-context))
  (include "src/syntax-bootstrap.scm")
  (include "src/cluck-standalone-prelude.scm"))

(include "src/cluck.scm")

(hash-table-set! *cluck-loaded-namespaces* 'cluck.string #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.state #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.history #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.view #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.panel #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.geometry #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.selection #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.actions #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.canvas #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.session #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.runtime #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.supervision #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.resources #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.render #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.status #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.commands #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.replay #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.edit #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.create #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.stroke #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.input #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.sdl3 #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw #t)

(include "src/cluck/string.clk")
(include "examples/cluck/draw/src/state.clk")
(include "examples/cluck/draw/src/history.clk")
(include "examples/cluck/draw/src/view.clk")
(include "examples/cluck/draw/src/panel.clk")
(include "examples/cluck/draw/src/geometry.clk")
(include "examples/cluck/draw/src/selection.clk")
(include "examples/cluck/draw/src/actions.clk")
(include "examples/cluck/draw/src/canvas.clk")
(include "examples/cluck/draw/src/session.clk")
(include "examples/cluck/draw/src/runtime.clk")
(include "examples/cluck/draw/src/supervision.clk")
(include "examples/cluck/draw/src/resources.clk")
(include "examples/cluck/draw/src/render.clk")
(include "examples/cluck/draw/src/status.clk")
(include "examples/cluck/draw/src/commands.clk")
(include "examples/cluck/draw/src/replay.clk")
(include "examples/cluck/draw/src/edit.clk")
(include "examples/cluck/draw/src/create.clk")
(include "examples/cluck/draw/src/stroke.clk")
(include "examples/cluck/draw/src/input.clk")
(include "examples/cluck/draw/src/sdl3.clk")
(include "examples/cluck/draw/main.clk")

(main (command-line-arguments))
