(import scheme
        (chicken base)
        (chicken load)
        (chicken process-context))

(begin-for-syntax
  (import (chicken file)
          (chicken process-context))
  (include "src/syntax-bootstrap.scm")
  (include "src/cluck-standalone-prelude.scm"))

(include "src/cluck.scm")

(hash-table-set! *cluck-loaded-namespaces* 'cluck.string #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.state #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.history #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.view #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.panel #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.geometry #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.selection #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.actions #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.canvas #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.session #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.runtime #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.supervision #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.render #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.status #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.commands #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.replay #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.edit #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.create #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.stroke #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.input #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw.sdl3 #t)
(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.draw #t)

(include "src/cluck/string.clk")
(include "src/cluck/examples/draw/state.clk")
(include "src/cluck/examples/draw/history.clk")
(include "src/cluck/examples/draw/view.clk")
(include "src/cluck/examples/draw/panel.clk")
(include "src/cluck/examples/draw/geometry.clk")
(include "src/cluck/examples/draw/selection.clk")
(include "src/cluck/examples/draw/actions.clk")
(include "src/cluck/examples/draw/canvas.clk")
(include "src/cluck/examples/draw/session.clk")
(include "src/cluck/examples/draw/runtime.clk")
(include "src/cluck/examples/draw/supervision.clk")
(include "src/cluck/examples/draw/render.clk")
(include "src/cluck/examples/draw/status.clk")
(include "src/cluck/examples/draw/commands.clk")
(include "src/cluck/examples/draw/replay.clk")
(include "src/cluck/examples/draw/edit.clk")
(include "src/cluck/examples/draw/create.clk")
(include "src/cluck/examples/draw/stroke.clk")
(include "src/cluck/examples/draw/input.clk")
(include "src/cluck/examples/draw/sdl3.clk")
(include "examples/cluck/draw/main.clk")

(main (command-line-arguments))
