;; Bootstrap aliases for the Ro CLI spike.
;;
;; This file is loaded before `src/app.clk` so the app can refer to the core
;; namespaces without depending on Chicken's namespace import handling during
;; the standalone build.

(define ro-help/root-help-lines (ns-resolve 'cluck.examples.ro.core.help 'root-help-lines))
(define ro-help/root-help-text (ns-resolve 'cluck.examples.ro.core.help 'root-help-text))
(define ro-help/root-help-output (ns-resolve 'cluck.examples.ro.core.help 'root-help-output))
(define ro-help/docs-help-lines (ns-resolve 'cluck.examples.ro.core.help 'docs-help-lines))
(define ro-help/docs-help-text (ns-resolve 'cluck.examples.ro.core.help 'docs-help-text))
(define ro-help/docs-help-output (ns-resolve 'cluck.examples.ro.core.help 'docs-help-output))
(define ro-help/docs-topics (ns-resolve 'cluck.examples.ro.core.help 'docs-topics))
(define ro-help/completion-top-commands (ns-resolve 'cluck.examples.ro.core.help 'completion-top-commands))
(define ro-help/completion-top-command-line (ns-resolve 'cluck.examples.ro.core.help 'completion-top-command-line))
(define ro-help/completion-doc-topics-line (ns-resolve 'cluck.examples.ro.core.help 'completion-doc-topics-line))
(define ro-help/completion-help-lines (ns-resolve 'cluck.examples.ro.core.help 'completion-help-lines))
(define ro-help/completion-help-text (ns-resolve 'cluck.examples.ro.core.help 'completion-help-text))
(define ro-help/completion-help-output (ns-resolve 'cluck.examples.ro.core.help 'completion-help-output))
(define ro-help/completion-bash-lines (ns-resolve 'cluck.examples.ro.core.help 'completion-bash-lines))
(define ro-help/completion-bash-output (ns-resolve 'cluck.examples.ro.core.help 'completion-bash-output))
(define ro-help/completion-zsh-lines (ns-resolve 'cluck.examples.ro.core.help 'completion-zsh-lines))
(define ro-help/completion-zsh-output (ns-resolve 'cluck.examples.ro.core.help 'completion-zsh-output))
(define ro-help/completion-fish-lines (ns-resolve 'cluck.examples.ro.core.help 'completion-fish-lines))
(define ro-help/completion-fish-output (ns-resolve 'cluck.examples.ro.core.help 'completion-fish-output))
(define ro-help/events-help-lines (ns-resolve 'cluck.examples.ro.core.help 'events-help-lines))
(define ro-help/events-help-text (ns-resolve 'cluck.examples.ro.core.help 'events-help-text))
(define ro-help/events-help-output (ns-resolve 'cluck.examples.ro.core.help 'events-help-output))
(define ro-help/workspace-help-lines (ns-resolve 'cluck.examples.ro.core.help 'workspace-help-lines))
(define ro-help/workspace-help-text (ns-resolve 'cluck.examples.ro.core.help 'workspace-help-text))
(define ro-help/workspace-help-output (ns-resolve 'cluck.examples.ro.core.help 'workspace-help-output))
(define ro-help/identity-help-lines (ns-resolve 'cluck.examples.ro.core.help 'identity-help-lines))
(define ro-help/identity-help-text (ns-resolve 'cluck.examples.ro.core.help 'identity-help-text))
(define ro-help/identity-help-output (ns-resolve 'cluck.examples.ro.core.help 'identity-help-output))
(define ro-help/status-help-lines (ns-resolve 'cluck.examples.ro.core.help 'status-help-lines))
(define ro-help/status-help-text (ns-resolve 'cluck.examples.ro.core.help 'status-help-text))
(define ro-help/status-help-output (ns-resolve 'cluck.examples.ro.core.help 'status-help-output))
(define ro-help/doctor-help-lines (ns-resolve 'cluck.examples.ro.core.help 'doctor-help-lines))
(define ro-help/doctor-help-text (ns-resolve 'cluck.examples.ro.core.help 'doctor-help-text))
(define ro-help/doctor-help-output (ns-resolve 'cluck.examples.ro.core.help 'doctor-help-output))
(define ro-help/reindex-help-lines (ns-resolve 'cluck.examples.ro.core.help 'reindex-help-lines))
(define ro-help/reindex-help-text (ns-resolve 'cluck.examples.ro.core.help 'reindex-help-text))
(define ro-help/reindex-help-output (ns-resolve 'cluck.examples.ro.core.help 'reindex-help-output))
(define ro-help/sync-help-lines (ns-resolve 'cluck.examples.ro.core.help 'sync-help-lines))
(define ro-help/sync-help-text (ns-resolve 'cluck.examples.ro.core.help 'sync-help-text))
(define ro-help/sync-help-output (ns-resolve 'cluck.examples.ro.core.help 'sync-help-output))
(define ro-help/docs-output (ns-resolve 'cluck.examples.ro.core.help 'docs-output))
(define ro-help/projects-help-lines (ns-resolve 'cluck.examples.ro.core.help 'projects-help-lines))
(define ro-help/projects-help-text (ns-resolve 'cluck.examples.ro.core.help 'projects-help-text))
(define ro-help/projects-help-output (ns-resolve 'cluck.examples.ro.core.help 'projects-help-output))
(define ro-help/help-request? (ns-resolve 'cluck.examples.ro.core.help 'help-request?))
(define ro-help/completion-help-request? (ns-resolve 'cluck.examples.ro.core.help 'completion-help-request?))
(define ro-help/completion-output (ns-resolve 'cluck.examples.ro.core.help 'completion-output))

(define ro-json/json-key->text (ns-resolve 'cluck.examples.ro.core.json 'json-key->text))
(define ro-json/json-key->symbol (ns-resolve 'cluck.examples.ro.core.json 'json-key->symbol))
(define ro-json/json-find-entry (ns-resolve 'cluck.examples.ro.core.json 'json-find-entry))
(define ro-json/json-field-value (ns-resolve 'cluck.examples.ro.core.json 'json-field-value))
(define ro-json/json-first-field-value (ns-resolve 'cluck.examples.ro.core.json 'json-first-field-value))
(define ro-json/cluck-value->json (ns-resolve 'cluck.examples.ro.core.json 'cluck-value->json))
(define ro-json/compact-json-step (ns-resolve 'cluck.examples.ro.core.json 'compact-json-step))
(define ro-json/compact-json-text (ns-resolve 'cluck.examples.ro.core.json 'compact-json-text))
(define ro-json/json-output (ns-resolve 'cluck.examples.ro.core.json 'json-output))
(define ro-json/json-write-output (ns-resolve 'cluck.examples.ro.core.json 'json-write-output))

(define ro-docs/docs-cli-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-cli-markdown))
(define ro-docs/docs-getting-started-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-getting-started-markdown))
(define ro-docs/docs-output-contract-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-output-contract-markdown))
(define ro-docs/docs-identity-ownership-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-identity-ownership-markdown))
(define ro-docs/docs-agent-runtimes-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-agent-runtimes-markdown))
(define ro-docs/docs-sync-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-sync-markdown))
(define ro-docs/docs-doctor-reindex-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-doctor-reindex-markdown))
(define ro-docs/docs-storage-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-storage-markdown))
(define ro-docs/docs-topic-markdown (ns-resolve 'cluck.examples.ro.core.docs 'docs-topic-markdown))
(define ro-docs/docs-topic-output (ns-resolve 'cluck.examples.ro.core.docs 'docs-topic-output))
(define ro-docs/docs-main-plan (ns-resolve 'cluck.examples.ro.core.docs 'docs-main-plan))

(define ro-workspace/workspace-detail-value (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-detail-value))
(define ro-workspace/workspace-current-detail (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-detail))
(define ro-workspace/workspace-current-info (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-info))
(define ro-workspace/workspace-current-name (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-name))
(define ro-workspace/workspace-current-path (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-path))
(define ro-workspace/actor-record (ns-resolve 'cluck.examples.ro.core.workspace 'actor-record))
(define ro-workspace/workspace-current-write-actor-id (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-write-actor-id))
(define ro-workspace/workspace-current-output (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-current-output))
(define ro-workspace/workspace-status-output (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-status-output))
(define ro-workspace/identity-list-output (ns-resolve 'cluck.examples.ro.core.workspace 'identity-list-output))
(define ro-workspace/identity-whoami-output (ns-resolve 'cluck.examples.ro.core.workspace 'identity-whoami-output))
(define ro-workspace/init-main-plan (ns-resolve 'cluck.examples.ro.core.workspace 'init-main-plan))
(define ro-workspace/status-main-plan (ns-resolve 'cluck.examples.ro.core.workspace 'status-main-plan))
(define ro-workspace/workspace-add-plan (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-add-plan))
(define ro-workspace/workspace-init-plan (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-init-plan))
(define ro-workspace/workspace-use-plan (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-use-plan))
(define ro-workspace/workspace-main-plan (ns-resolve 'cluck.examples.ro.core.workspace 'workspace-main-plan))
(define ro-workspace/identity-main-plan (ns-resolve 'cluck.examples.ro.core.workspace 'identity-main-plan))

(define ro-projects/json-key->text (ns-resolve 'cluck.examples.ro.core.projects 'json-key->text))
(define ro-projects/json-find-entry (ns-resolve 'cluck.examples.ro.core.projects 'json-find-entry))
(define ro-projects/json-field-value (ns-resolve 'cluck.examples.ro.core.projects 'json-field-value))
(define ro-projects/compact-json-step (ns-resolve 'cluck.examples.ro.core.projects 'compact-json-step))
(define ro-projects/compact-json-text (ns-resolve 'cluck.examples.ro.core.projects 'compact-json-text))
(define ro-projects/json-write-output (ns-resolve 'cluck.examples.ro.core.projects 'json-write-output))
(define ro-projects/project-summary (ns-resolve 'cluck.examples.ro.core.projects 'project-summary))
(define ro-projects/projects-list-output (ns-resolve 'cluck.examples.ro.core.projects 'projects-list-output))
(define ro-projects/projects-current-output (ns-resolve 'cluck.examples.ro.core.projects 'projects-current-output))
(define ro-projects/projects-main-plan (ns-resolve 'cluck.examples.ro.core.projects 'projects-main-plan))

(define ro-worklog/help-flag? (ns-resolve 'cluck.examples.ro.core.worklog 'help-flag?))
(define ro-worklog/any-help-arg? (ns-resolve 'cluck.examples.ro.core.worklog 'any-help-arg?))
(define ro-worklog/worklog-help-lines (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-help-lines))
(define ro-worklog/worklog-help-text (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-help-text))
(define ro-worklog/worklog-help-output (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-help-output))
(define ro-worklog/worklog-list-plan (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-list-plan))
(define ro-worklog/worklog-add-plan (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-add-plan))
(define ro-worklog/worklog-main-plan (ns-resolve 'cluck.examples.ro.core.worklog 'worklog-main-plan))

(define ro-comments/comments-help-lines (ns-resolve 'cluck.examples.ro.core.comments 'comments-help-lines))
(define ro-comments/comments-help-text (ns-resolve 'cluck.examples.ro.core.comments 'comments-help-text))
(define ro-comments/comments-help-output (ns-resolve 'cluck.examples.ro.core.comments 'comments-help-output))
(define ro-comments/comments-list-plan (ns-resolve 'cluck.examples.ro.core.comments 'comments-list-plan))
(define ro-comments/comments-add-plan (ns-resolve 'cluck.examples.ro.core.comments 'comments-add-plan))
(define ro-comments/comments-main-plan (ns-resolve 'cluck.examples.ro.core.comments 'comments-main-plan))

(define ro-discuss/discuss-help-lines (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-help-lines))
(define ro-discuss/discuss-help-text (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-help-text))
(define ro-discuss/discuss-help-output (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-help-output))
(define ro-discuss/discuss-list-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-list-plan))
(define ro-discuss/discuss-show-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-show-plan))
(define ro-discuss/discuss-start-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-start-plan))
(define ro-discuss/discuss-promote-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-promote-plan))
(define ro-discuss/discuss-resolve-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-resolve-plan))
(define ro-discuss/discuss-reopen-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-reopen-plan))
(define ro-discuss/discuss-main-plan (ns-resolve 'cluck.examples.ro.core.discuss 'discuss-main-plan))

(define ro-deps/deps-help-lines (ns-resolve 'cluck.examples.ro.core.deps 'deps-help-lines))
(define ro-deps/deps-help-text (ns-resolve 'cluck.examples.ro.core.deps 'deps-help-text))
(define ro-deps/deps-help-output (ns-resolve 'cluck.examples.ro.core.deps 'deps-help-output))
(define ro-deps/deps-add-plan (ns-resolve 'cluck.examples.ro.core.deps 'deps-add-plan))
(define ro-deps/deps-list-plan (ns-resolve 'cluck.examples.ro.core.deps 'deps-list-plan))
(define ro-deps/deps-tree-plan (ns-resolve 'cluck.examples.ro.core.deps 'deps-tree-plan))
(define ro-deps/deps-cycles-plan (ns-resolve 'cluck.examples.ro.core.deps 'deps-cycles-plan))
(define ro-deps/deps-main-plan (ns-resolve 'cluck.examples.ro.core.deps 'deps-main-plan))

(define ro-publish/publish-help-lines (ns-resolve 'cluck.examples.ro.core.publish 'publish-help-lines))
(define ro-publish/publish-help-text (ns-resolve 'cluck.examples.ro.core.publish 'publish-help-text))
(define ro-publish/publish-help-output (ns-resolve 'cluck.examples.ro.core.publish 'publish-help-output))
(define ro-publish/publish-item-plan (ns-resolve 'cluck.examples.ro.core.publish 'publish-item-plan))
(define ro-publish/publish-outline-plan (ns-resolve 'cluck.examples.ro.core.publish 'publish-outline-plan))
(define ro-publish/publish-main-plan (ns-resolve 'cluck.examples.ro.core.publish 'publish-main-plan))

(define ro-capture/capture-help-lines (ns-resolve 'cluck.examples.ro.core.capture 'capture-help-lines))
(define ro-capture/capture-help-text (ns-resolve 'cluck.examples.ro.core.capture 'capture-help-text))
(define ro-capture/capture-help-output (ns-resolve 'cluck.examples.ro.core.capture 'capture-help-output))
(define ro-capture/capture-main-plan (ns-resolve 'cluck.examples.ro.core.capture 'capture-main-plan))

(define ro-attachments/attachments-help-lines (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-help-lines))
(define ro-attachments/attachments-help-text (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-help-text))
(define ro-attachments/attachments-help-output (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-help-output))
(define ro-attachments/attachments-add-plan (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-add-plan))
(define ro-attachments/attachments-list-plan (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-list-plan))
(define ro-attachments/attachments-open-plan (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-open-plan))
(define ro-attachments/attachments-export-plan (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-export-plan))
(define ro-attachments/attachments-main-plan (ns-resolve 'cluck.examples.ro.core.attachments 'attachments-main-plan))

(define ro-clock/clock-help-lines (ns-resolve 'cluck.examples.ro.core.clock 'clock-help-lines))
(define ro-clock/clock-help-text (ns-resolve 'cluck.examples.ro.core.clock 'clock-help-text))
(define ro-clock/clock-help-output (ns-resolve 'cluck.examples.ro.core.clock 'clock-help-output))
(define ro-clock/clock-main-plan (ns-resolve 'cluck.examples.ro.core.clock 'clock-main-plan))

(define ro-agenda/agenda-help-lines (ns-resolve 'cluck.examples.ro.core.agenda 'agenda-help-lines))
(define ro-agenda/agenda-help-text (ns-resolve 'cluck.examples.ro.core.agenda 'agenda-help-text))
(define ro-agenda/agenda-help-output (ns-resolve 'cluck.examples.ro.core.agenda 'agenda-help-output))
(define ro-agenda/agenda-main-plan (ns-resolve 'cluck.examples.ro.core.agenda 'agenda-main-plan))

(define ro-outlines/help-flag? (ns-resolve 'cluck.examples.ro.core.outlines 'help-flag?))
(define ro-outlines/any-help-arg? (ns-resolve 'cluck.examples.ro.core.outlines 'any-help-arg?))
(define ro-outlines/outlines-help-lines (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-help-lines))
(define ro-outlines/outlines-help-text (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-help-text))
(define ro-outlines/outlines-help-output (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-help-output))
(define ro-outlines/outline-status-id-from-label (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-id-from-label))
(define ro-outlines/outline-status-def-record (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-def-record))
(define ro-outlines/outline-default-status-defs (ns-resolve 'cluck.examples.ro.core.outlines 'outline-default-status-defs))
(define ro-outlines/outline-status-def-summary (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-def-summary))
(define ro-outlines/outline-status-defs-summary (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-defs-summary))
(define ro-outlines/outline-summary (ns-resolve 'cluck.examples.ro.core.outlines 'outline-summary))
(define ro-outlines/outline-summary<? (ns-resolve 'cluck.examples.ro.core.outlines 'outline-summary<?))
(define ro-outlines/outlines-list-output (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-list-output))
(define ro-outlines/outlines-show-output (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-show-output))
(define ro-outlines/outlines-status-list-output (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-list-output))
(define ro-outlines/outline-status-defs-add (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-defs-add))
(define ro-outlines/outline-status-defs-update (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-defs-update))
(define ro-outlines/outline-status-defs-remove (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-defs-remove))
(define ro-outlines/outline-status-defs-reorder (ns-resolve 'cluck.examples.ro.core.outlines 'outline-status-defs-reorder))
(define ro-outlines/outlines-create-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-create-plan))
(define ro-outlines/outlines-list-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-list-plan))
(define ro-outlines/outlines-show-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-show-plan))
(define ro-outlines/outlines-archive-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-archive-plan))
(define ro-outlines/outlines-status-list-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-list-plan))
(define ro-outlines/outlines-status-add-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-add-plan))
(define ro-outlines/outlines-status-update-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-update-plan))
(define ro-outlines/outlines-status-remove-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-remove-plan))
(define ro-outlines/outlines-status-reorder-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-reorder-plan))
(define ro-outlines/outlines-status-main-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-status-main-plan))
(define ro-outlines/outlines-main-plan (ns-resolve 'cluck.examples.ro.core.outlines 'outlines-main-plan))

(define ro-items/help-flag? (ns-resolve 'cluck.examples.ro.core.items 'help-flag?))
(define ro-items/any-help-arg? (ns-resolve 'cluck.examples.ro.core.items 'any-help-arg?))
(define ro-items/items-help-lines (ns-resolve 'cluck.examples.ro.core.items 'items-help-lines))
(define ro-items/items-help-text (ns-resolve 'cluck.examples.ro.core.items 'items-help-text))
(define ro-items/items-help-output (ns-resolve 'cluck.examples.ro.core.items 'items-help-output))
(define ro-items/items-show-hints (ns-resolve 'cluck.examples.ro.core.items 'items-show-hints))
(define ro-items/items-list-hints (ns-resolve 'cluck.examples.ro.core.items 'items-list-hints))
(define ro-items/items-ready-hints (ns-resolve 'cluck.examples.ro.core.items 'items-ready-hints))
(define ro-items/items-show-output (ns-resolve 'cluck.examples.ro.core.items 'items-show-output))
(define ro-items/items-list-output (ns-resolve 'cluck.examples.ro.core.items 'items-list-output))
(define ro-items/items-ready-output (ns-resolve 'cluck.examples.ro.core.items 'items-ready-output))
(define ro-items/items-events-output (ns-resolve 'cluck.examples.ro.core.items 'items-events-output))
(define ro-items/item-show-summary (ns-resolve 'cluck.examples.ro.core.items 'item-show-summary))
(define ro-items/items-show-plan (ns-resolve 'cluck.examples.ro.core.items 'items-show-plan))
(define ro-items/items-list-plan (ns-resolve 'cluck.examples.ro.core.items 'items-list-plan))
(define ro-items/items-ready-plan (ns-resolve 'cluck.examples.ro.core.items 'items-ready-plan))
(define ro-items/items-events-plan (ns-resolve 'cluck.examples.ro.core.items 'items-events-plan))
(define ro-items/items-main-plan (ns-resolve 'cluck.examples.ro.core.items 'items-main-plan))
(define ro-items/item-main-plan (ns-resolve 'cluck.examples.ro.core.items 'item-main-plan))

(define ro-events/json-key->text (ns-resolve 'cluck.examples.ro.core.events 'json-key->text))
(define ro-events/json-find-entry (ns-resolve 'cluck.examples.ro.core.events 'json-find-entry))

(define ro-agent/agent-help-lines (ns-resolve 'cluck.examples.ro.core.agent 'agent-help-lines))
(define ro-agent/agent-help-text (ns-resolve 'cluck.examples.ro.core.agent 'agent-help-text))
(define ro-agent/agent-help-output (ns-resolve 'cluck.examples.ro.core.agent 'agent-help-output))
(define ro-agent/agent-main-plan (ns-resolve 'cluck.examples.ro.core.agent 'agent-main-plan))
(define ro-events/json-field-value (ns-resolve 'cluck.examples.ro.core.events 'json-field-value))
(define ro-events/json-first-field-value (ns-resolve 'cluck.examples.ro.core.events 'json-first-field-value))
(define ro-events/compact-json-step (ns-resolve 'cluck.examples.ro.core.events 'compact-json-step))
(define ro-events/compact-json-text (ns-resolve 'cluck.examples.ro.core.events 'compact-json-text))
(define ro-events/event-line->record (ns-resolve 'cluck.examples.ro.core.events 'event-line->record))
(define ro-events/event-materialize-record (ns-resolve 'cluck.examples.ro.core.events 'event-materialize-record))
(define ro-events/event-record<? (ns-resolve 'cluck.examples.ro.core.events 'event-record<?))
(define ro-events/events-merge-record-lists (ns-resolve 'cluck.examples.ro.core.events 'events-merge-record-lists))
(define ro-events/events-split-records (ns-resolve 'cluck.examples.ro.core.events 'events-split-records))
(define ro-events/events-sort-records (ns-resolve 'cluck.examples.ro.core.events 'events-sort-records))
(define ro-events/events-default-limit (ns-resolve 'cluck.examples.ro.core.events 'events-default-limit))
(define ro-events/events-main-plan (ns-resolve 'cluck.examples.ro.core.events 'events-main-plan))

(define ro-sync/git-status-line-unmerged? (ns-resolve 'cluck.examples.ro.core.sync 'git-status-line-unmerged?))
(define ro-sync/git-status-flags (ns-resolve 'cluck.examples.ro.core.sync 'git-status-flags))
(define ro-sync/git-ahead-behind (ns-resolve 'cluck.examples.ro.core.sync 'git-ahead-behind))
(define ro-sync/git-sync-empty-status (ns-resolve 'cluck.examples.ro.core.sync 'git-sync-empty-status))
(define ro-sync/sync-main-plan (ns-resolve 'cluck.examples.ro.core.sync 'sync-main-plan))

(define ro-doctor/json-key->text (ns-resolve 'cluck.examples.ro.core.doctor 'json-key->text))
(define ro-doctor/json-find-entry (ns-resolve 'cluck.examples.ro.core.doctor 'json-find-entry))
(define ro-doctor/json-field-value (ns-resolve 'cluck.examples.ro.core.doctor 'json-field-value))
(define ro-doctor/json-first-field-value (ns-resolve 'cluck.examples.ro.core.doctor 'json-first-field-value))
(define ro-doctor/doctor-event-entity-kind (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-event-entity-kind))
(define ro-doctor/doctor-make-issue (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-make-issue))
(define ro-doctor/doctor-issue-from-record (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-issue-from-record))
(define ro-doctor/doctor-parse-event-record (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-parse-event-record))
(define ro-doctor/doctor-key-count<? (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-key-count<?))
(define ro-doctor/doctor-event-summary<? (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-event-summary<?))
(define ro-doctor/doctor-dedupe-file<? (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-dedupe-file<?))
(define ro-doctor/doctor-dedupe-event<? (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-dedupe-event<?))
(define ro-doctor/doctor-count-objects (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-count-objects))
(define ro-doctor/doctor-duplicate-event-summary (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-duplicate-event-summary))
(define ro-doctor/doctor-has-errors? (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-has-errors?))
(define ro-doctor/doctor-summary-from-issues (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-summary-from-issues))
(define ro-doctor/doctor-dedupe-plan-from-issues (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-dedupe-plan-from-issues))
(define ro-doctor/doctor-main-plan (ns-resolve 'cluck.examples.ro.core.doctor 'doctor-main-plan))

(define ro-reindex/reindex-recognized-types (ns-resolve 'cluck.examples.ro.core.reindex 'reindex-recognized-types))
(define ro-reindex/reindex-type-recognized? (ns-resolve 'cluck.examples.ro.core.reindex 'reindex-type-recognized?))
(define ro-reindex/reindex-main-plan (ns-resolve 'cluck.examples.ro.core.reindex 'reindex-main-plan))

(define ro-route/main-route (ns-resolve 'cluck.examples.ro.core.route 'main-route))
