(import scheme
        (chicken base)
        (chicken file)
        (chicken load)
        (chicken process-context)
        (prefix json json:)
        (prefix ncurses nc:)
        (prefix sqlite3 db:))

(begin-for-syntax
  (import (chicken file)
          (chicken process-context))
  (include "src/syntax-bootstrap.scm")
  (include "src/cluck-standalone-prelude.scm"))

(include "src/cluck.scm")
(include "src/cluck/string.clk")
(hash-table-set! *cluck-loaded-namespaces* 'cluck.string #t)

(include "src/cluck/fs.clk")
(hash-table-set! *cluck-loaded-namespaces* 'cluck.fs #t)

(include "src/cluck/io.clk")
(hash-table-set! *cluck-loaded-namespaces* 'cluck.io #t)

(define json/json-read json:json-read)
(define json/json-write json:json-write)

(hash-table-set! *cluck-loaded-namespaces* 'cluck.examples.ro.app #t)

(define nc/A_BOLD nc:A_BOLD)
(define nc/A_REVERSE nc:A_REVERSE)
(define nc/KEY_BACKSPACE nc:KEY_BACKSPACE)
(define nc/KEY_DC nc:KEY_DC)
(define nc/KEY_DOWN nc:KEY_DOWN)
(define nc/KEY_END nc:KEY_END)
(define nc/KEY_ENTER nc:KEY_ENTER)
(define nc/KEY_HOME nc:KEY_HOME)
(define nc/KEY_LEFT nc:KEY_LEFT)
(define nc/KEY_NPAGE nc:KEY_NPAGE)
(define nc/KEY_PPAGE nc:KEY_PPAGE)
(define nc/KEY_RESIZE nc:KEY_RESIZE)
(define nc/KEY_RIGHT nc:KEY_RIGHT)
(define nc/KEY_UP nc:KEY_UP)
(define nc/attroff nc:attroff)
(define nc/attron nc:attron)
(define nc/cbreak nc:cbreak)
(define nc/curs_set nc:curs_set)
(define nc/endwin nc:endwin)
(define nc/erase nc:erase)
(define nc/getch nc:getch)
(define nc/getmaxyx nc:getmaxyx)
(define nc/initscr nc:initscr)
(define nc/keyname nc:keyname)
(define nc/keypad nc:keypad)
(define nc/move nc:move)
(define nc/mvaddstr nc:mvaddstr)
(define nc/noecho nc:noecho)
(define nc/refresh nc:refresh)
(define nc/stdscr nc:stdscr)

(define db/execute db:execute)
(define db/finalize! db:finalize!)
(define db/first-result db:first-result)
(define db/last-insert-rowid db:last-insert-rowid)
(define db/make-busy-timeout db:make-busy-timeout)
(define db/map-row db:map-row)
(define db/open-database db:open-database)
(define db/set-busy-handler! db:set-busy-handler!)
(define db/update db:update)
(define db/with-transaction db:with-transaction)

(include "examples/cluck/ro/src/app.clk")
(include "examples/cluck/ro/main.clk")

(let ((args (command-line-arguments)))
  (let ((result (main args)))
    (if (number? result)
        (exit result)
        (if (and (pair? args)
                 (string=? (car args) "completion")
                 (null? (cdr args)))
            (exit 1)
            #t))))
