(import (chicken file)
        (chicken load)
        (chicken process-context))

(define (script-root)
  (let loop ((i (- (string-length (program-name)) 1)))
    (if (< i 0)
        (string-append (current-directory) "/")
        (if (char=? (string-ref (program-name) i) #\/)
            (substring (program-name) 0 (+ i 1))
            (loop (- i 1))))))

(let ((root (script-root)))
  (load (string-append root "../bootstrap.scm"))
  (let* ((project-root (cluck-bootstrap-root))
         (cluck-root (cluck-bootstrap-load-runtime! project-root)))
    (handle-exceptions exn #t
      (create-directory (string-append project-root "build")))
    (cluck-with-module-search-root
     cluck-root
     (lambda ()
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/cli/cmdspec.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/cli/ro_spec.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/cli.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/cli/completions.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/commands.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/json.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/docs.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/help.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/workspace.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/projects.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/worklog.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/comments.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/discuss.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/deps.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/publish.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/capture.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/attachments.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/clock.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/agenda.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/outlines.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/items.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/events.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/agent.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/sync.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/doctor.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/reindex.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/core/route.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/bootstrap-core-aliases.scm")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/src/app.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/src/tui.clk")
       (cluck-bootstrap-load-app! project-root "examples/cluck/ro/main.clk")
       (let ((args (command-line-arguments)))
         (let ((result ((ns-resolve 'cluck.examples.ro 'main) args)))
           (if (number? result)
               (exit result)
               (if (and (pair? args)
                        (string=? (car args) "completion")
                        (null? (cdr args)))
                   (exit 1)
                   #t))))))))
